[package]
name = "ffmpeg-extractor"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
pkg-config = "0.3.31"
[build-dependencies]
bindgen = "0.71.1"
cc = "1.0"
pkg-config = "0.3"

[lib]
name = "ffmpeg_extractor"
crate-type = ["lib"]
