[package]
name = "ffmpeg-extractor"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
[build-dependencies]
bindgen = "0.71.1"
cc = "1.0"
ffmpeg-next = "7.1.0"

[lib]
name = "ffmpeg_extractor"
crate-type = ["lib"]